use crate::ast::*;
use crate::typechecker::{FunctionSignature, TypeDefinition, EnumVariantInfo};
use std::collections::HashMap;
use std::fmt::Write;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CodegenError {
    #[error("Type not found: {0}")]
    TypeNotFound(String),

    #[error("Function not found: {0}")]
    FunctionNotFound(String),

    #[error("Variable not found: {0}")]
    VariableNotFound(String),

    #[error("Cannot generate code for expression")]
    CannotGenerateExpression,
}

pub struct CCodegen {
    output: String,
    indent: usize,
    types: HashMap<String, TypeDefinition>,
    functions: HashMap<String, FunctionSignature>,
    constants: HashMap<String, (Type, Expr)>,
    variable_types: HashMap<String, Type>,
}

impl CCodegen {
    pub fn new() -> Self {
        CCodegen {
            output: String::new(),
            indent: 0,
            types: HashMap::new(),
            functions: HashMap::new(),
            constants: HashMap::new(),
            variable_types: HashMap::new(),
        }
    }

    pub fn compile(&mut self, program: &Program) -> Result<String, CodegenError> {
        self.output.clear();

        // Header with GNU extensions for Statement Expressions
        writeln!(self.output, "// Generated by glyphc v0.1.0").unwrap();
        writeln!(self.output, "#include <stdio.h>").unwrap();
        writeln!(self.output, "#include <stdlib.h>").unwrap();
        writeln!(self.output, "#include <string.h>").unwrap();
        writeln!(self.output, "#include <stdint.h>").unwrap();
        writeln!(self.output, "#include <math.h>").unwrap();
        writeln!(self.output, "#include <sys/stat.h>").unwrap();
        writeln!(self.output, "").unwrap();

        // Forward declarations for all built-in runtime functions
        writeln!(self.output, "// IO").unwrap();
        writeln!(self.output, "void glyph_println(const char* msg);").unwrap();
        writeln!(self.output, "void glyph_eprintln(const char* msg);").unwrap();
        writeln!(self.output, "void glyph_print_int(int64_t v);").unwrap();
        writeln!(self.output, "void glyph_print_float(double v);").unwrap();
        writeln!(self.output, "void glyph_print_bool(int v);").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// String").unwrap();
        writeln!(self.output, "char* glyph_concat_strings(const char* a, const char* b);").unwrap();
        writeln!(self.output, "char* glyph_int_to_string(int64_t v);").unwrap();
        writeln!(self.output, "char* glyph_float_to_string(double v);").unwrap();
        writeln!(self.output, "char* glyph_bool_to_string(int v);").unwrap();
        writeln!(self.output, "int64_t glyph_strlen(const char* s);").unwrap();
        writeln!(self.output, "char* glyph_substring(const char* s, int64_t start, int64_t end);").unwrap();
        writeln!(self.output, "int glyph_str_contains(const char* s, const char* sub);").unwrap();
        writeln!(self.output, "int glyph_str_starts_with(const char* s, const char* p);").unwrap();
        writeln!(self.output, "int glyph_str_ends_with(const char* s, const char* sfx);").unwrap();
        writeln!(self.output, "char* glyph_str_trim(const char* s);").unwrap();
        writeln!(self.output, "char* glyph_str_to_upper(const char* s);").unwrap();
        writeln!(self.output, "char* glyph_str_to_lower(const char* s);").unwrap();
        writeln!(self.output, "char glyph_char_at(const char* s, int64_t i);").unwrap();
        writeln!(self.output, "typedef struct {{ int64_t ok; int64_t val; }} OptionInt;").unwrap();
        writeln!(self.output, "OptionInt glyph_parse_int(const char* s);").unwrap();
        writeln!(self.output, "typedef struct {{ int ok; double val; }} OptionFloat;").unwrap();
        writeln!(self.output, "OptionFloat glyph_parse_float(const char* s);").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// Math").unwrap();
        writeln!(self.output, "double glyph_abs(double x);").unwrap();
        writeln!(self.output, "double glyph_min(double a, double b);").unwrap();
        writeln!(self.output, "double glyph_max(double a, double b);").unwrap();
        writeln!(self.output, "double glyph_sqrt(double x);").unwrap();
        writeln!(self.output, "double glyph_pow(double b, double e);").unwrap();
        writeln!(self.output, "double glyph_floor(double x);").unwrap();
        writeln!(self.output, "double glyph_ceil(double x);").unwrap();
        writeln!(self.output, "double glyph_round(double x);").unwrap();
        writeln!(self.output, "double glyph_log(double x);").unwrap();
        writeln!(self.output, "double glyph_log2(double x);").unwrap();
        writeln!(self.output, "double glyph_log10(double x);").unwrap();
        writeln!(self.output, "double glyph_sin(double x);").unwrap();
        writeln!(self.output, "double glyph_cos(double x);").unwrap();
        writeln!(self.output, "double glyph_tan(double x);").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// File I/O").unwrap();
        writeln!(self.output, "char* glyph_file_read(const char* path);").unwrap();
        writeln!(self.output, "int glyph_file_write(const char* path, const char* content);").unwrap();
        writeln!(self.output, "int glyph_file_append(const char* path, const char* content);").unwrap();
        writeln!(self.output, "int glyph_file_exists(const char* path);").unwrap();
        writeln!(self.output, "int glyph_create_dir(const char* path);").unwrap();
        writeln!(self.output, "int glyph_remove_file(const char* path);").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// Memory").unwrap();
        writeln!(self.output, "void* glyph_alloc(int64_t size);").unwrap();
        writeln!(self.output, "void glyph_free(void* p);").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// Assert").unwrap();
        writeln!(self.output, "void glyph_assert(int cond, const char* msg);").unwrap();
        writeln!(self.output, "void glyph_assert_eq(const char* a, const char* b, const char* msg);").unwrap();
        writeln!(self.output, "void glyph_assert_ne(const char* a, const char* b, const char* msg);").unwrap();
        writeln!(self.output, "").unwrap();

        // Collect type definitions and function signatures
        for item in &program.items {
            match item {
                TopLevelItem::Struct { name, fields, .. } => {
                    self.types.insert(
                        name.clone(),
                        TypeDefinition::Struct {
                            fields: fields.clone(),
                        },
                    );
                }
                TopLevelItem::Enum { name, variants, .. } => {
                    let enum_variants = variants
                        .iter()
                        .map(|v| EnumVariantInfo {
                            name: v.name.clone(),
                            data: v.data.clone(),
                        })
                        .collect();
                    self.types.insert(
                        name.clone(),
                        TypeDefinition::Enum {
                            variants: enum_variants,
                        },
                    );
                }
                TopLevelItem::Function {
                    name,
                    params,
                    return_type,
                    is_async,
                    ..
                } => {
                    let sig = FunctionSignature {
                        params: params
                            .iter()
                            .map(|p| (p.name.clone(), p.ty.clone(), p.is_move))
                            .collect(),
                        return_type: return_type.clone(),
                        is_async: *is_async,
                    };
                    self.functions.insert(name.clone(), sig);
                }
                TopLevelItem::Impl {
                    type_name,
                    methods,
                    ..
                } => {
                    for method in methods {
                        let sig = FunctionSignature {
                            params: method.params
                                .iter()
                                .map(|p| (p.name.clone(), p.ty.clone(), p.is_move))
                                .collect(),
                            return_type: method.return_type.clone(),
                            is_async: method.is_async,
                        };
                        let full_name = format!("{}.{}", type_name, method.name);
                        self.functions.insert(full_name, sig);
                    }
                }
                TopLevelItem::Const { name, ty, value, .. } => {
                    self.constants.insert(name.clone(), (ty.clone(), value.clone()));
                    self.functions.insert(
                        name.clone(),
                        FunctionSignature {
                            params: vec![],
                            return_type: Some(ty.clone()),
                            is_async: false,
                        },
                    );
                }
                _ => {}
            }
        }

        // Enum definitions (tagged unions)
        for item in &program.items {
            if let TopLevelItem::Enum { name, variants, .. } = item {
                self.emit_enum_definition(name, variants)?;
            }
        }

        // Struct definitions
        for item in &program.items {
            if let TopLevelItem::Struct { name, fields, .. } = item {
                self.emit_struct_definition(name, fields)?;
            }
        }

        writeln!(self.output, "").unwrap();

        // Forward declarations
        for item in &program.items {
            if let TopLevelItem::Function {
                name,
                params,
                return_type,
                ..
            } = item
            {
                self.emit_function_declaration(name, params, return_type.as_ref())?;
                writeln!(self.output, ";").unwrap();
            }
        }

        writeln!(self.output, "").unwrap();

        // Function implementations
        for item in &program.items {
            match item {
                TopLevelItem::Function {
                    name,
                    params,
                    body,
                    return_type,
                    ..
                } => {
                    self.emit_function_implementation(name, params, body, return_type.as_ref())?;
                }
                TopLevelItem::Impl {
                    type_name,
                    methods,
                    ..
                } => {
                    for method in methods {
                        let full_name = format!("{}.{}", type_name, method.name);
                        self.emit_function_implementation(
                            &full_name,
                            &method.params,
                            &method.body,
                            method.return_type.as_ref(),
                        )?;
                    }
                }
                _ => {}
            }
        }

        // Add built-in function implementations
        self.emit_builtin_functions();

        Ok(self.output.clone())
    }

    fn emit_enum_definition(
        &mut self,
        name: &str,
        variants: &[EnumVariant],
    ) -> Result<(), CodegenError> {
        // Tag enum
        writeln!(self.output, "// Enum: {}", name).unwrap();
        writeln!(self.output, "typedef enum {{").unwrap();
        self.indent += 1;
        for variant in variants {
            self.emit_indent();
            writeln!(self.output, "{}_Tag_{},", name, variant.name).unwrap();
        }
        self.indent -= 1;
        writeln!(self.output, "}} {}_Tag;", name).unwrap();
        writeln!(self.output, "").unwrap();

        // Data union (if any variant has data)
        let has_data = variants.iter().any(|v| v.data.is_some());
        if has_data {
            writeln!(self.output, "typedef union {{").unwrap();
            self.indent += 1;
            for variant in variants {
                if let Some(data) = &variant.data {
                    self.emit_indent();
                    write!(self.output, "struct {{ ").unwrap();
                    for (i, ty) in data.iter().enumerate() {
                        if i > 0 {
                            write!(self.output, " ").unwrap();
                        }
                        write!(self.output, "{} field{};", self.type_to_c(ty), i).unwrap();
                    }
                    writeln!(self.output, " }} {}; // {}", variant.name, variant.name).unwrap();
                }
            }
            self.indent -= 1;
            writeln!(self.output, "}} {}_Data;", name).unwrap();
            writeln!(self.output, "").unwrap();
        }

        // Combined struct
        writeln!(self.output, "typedef struct {{").unwrap();
        self.indent += 1;
        self.emit_indent();
        writeln!(self.output, "{}_Tag tag;", name).unwrap();
        if has_data {
            self.emit_indent();
            writeln!(self.output, "{}_Data data;", name).unwrap();
        }
        self.indent -= 1;
        writeln!(self.output, "}} {};", name).unwrap();
        writeln!(self.output, "").unwrap();

        Ok(())
    }

    fn emit_function_declaration(
        &mut self,
        name: &str,
        params: &[FunctionParam],
        return_type: Option<&Type>,
    ) -> Result<(), CodegenError> {
        // Special case: main function must return int in C
        let ret_type_str = if name == "main" {
            "int".to_string()
        } else {
            match return_type {
                Some(ty) => self.type_to_c(ty),
                None => "void".to_string(),
            }
        };

        write!(self.output, "{} {}(", ret_type_str, name).unwrap();

        for (i, param) in params.iter().enumerate() {
            if i > 0 {
                write!(self.output, ", ").unwrap();
            }
            write!(self.output, "{} {}", self.type_to_c(&param.ty), param.name).unwrap();
        }

        write!(self.output, ")").unwrap();

        Ok(())
    }

    fn emit_struct_definition(
        &mut self,
        name: &str,
        fields: &[(String, Type)],
    ) -> Result<(), CodegenError> {
        writeln!(self.output, "typedef struct {{").unwrap();
        self.indent += 1;

        for (field_name, field_type) in fields {
            self.emit_indent();
            writeln!(self.output, "{} {};", self.type_to_c(field_type), field_name).unwrap();
        }

        self.indent -= 1;
        writeln!(self.output, "}} {};", name).unwrap();
        writeln!(self.output, "").unwrap();

        Ok(())
    }

    fn emit_function_implementation(
        &mut self,
        name: &str,
        params: &[FunctionParam],
        body: &[Stmt],
        return_type: Option<&Type>,
    ) -> Result<(), CodegenError> {
        self.emit_function_declaration(name, params, return_type)?;
        writeln!(self.output, " {{").unwrap();
        self.indent += 1;

        for param in params {
            self.variable_types.insert(param.name.clone(), param.ty.clone());
        }

        for (i, stmt) in body.iter().enumerate() {
            let is_last = i == body.len() - 1;
            // If this is the last statement and it's an expression, add return
            // Only for non-void return types
            if is_last && return_type.is_some() && !matches!(return_type, Some(Type::Void)) {
                if let Stmt::Expression(expr) = stmt {
                    self.emit_indent();
                    write!(self.output, "return ").unwrap();
                    self.emit_expression(expr)?;
                    writeln!(self.output, ";").unwrap();
                    continue;
                }
            }
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        Ok(())
    }

    fn emit_statement(&mut self, stmt: &Stmt) -> Result<(), CodegenError> {
        match stmt {
            Stmt::Let {
                name,
                ty,
                value,
                mutable: _,
            } => {
                // Track variable type for match codegen reference detection
                if let Some(t) = ty {
                    self.variable_types.insert(name.clone(), t.clone());
                }
                self.emit_indent();
                let ty_str = match ty {
                    Some(t) => self.type_to_c(t),
                    None => "auto".to_string(),
                };
                write!(self.output, "{} {} = ", ty_str, name).unwrap();
                self.emit_expression(value)?;
                writeln!(self.output, ";").unwrap();
            }
            Stmt::Assignment { target, value } => {
                self.emit_indent();
                self.emit_expression(target)?;
                write!(self.output, " = ").unwrap();
                self.emit_expression(value)?;
                writeln!(self.output, ";").unwrap();
            }
            Stmt::Expression(expr) => {
                self.emit_indent();
                self.emit_expression(expr)?;
                writeln!(self.output, ";").unwrap();
            }
            Stmt::Return(expr) => {
                self.emit_indent();
                write!(self.output, "return").unwrap();
                if let Some(e) = expr {
                    write!(self.output, " ").unwrap();
                    self.emit_expression(e)?;
                }
                writeln!(self.output, ";").unwrap();
            }
            Stmt::Break => {
                self.emit_indent();
                writeln!(self.output, "break;").unwrap();
            }
            Stmt::Continue => {
                self.emit_indent();
                writeln!(self.output, "continue;").unwrap();
            }
            Stmt::Loop(body) => {
                self.emit_indent();
                writeln!(self.output, "while (1) {{").unwrap();
                self.indent += 1;

                for stmt in body {
                    self.emit_statement(stmt)?;
                }

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}}").unwrap();
            }
            Stmt::While { condition, body } => {
                self.emit_indent();
                write!(self.output, "while (").unwrap();
                self.emit_expression(condition)?;
                writeln!(self.output, ") {{").unwrap();
                self.indent += 1;

                for stmt in body {
                    self.emit_statement(stmt)?;
                }

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}}").unwrap();
            }
            Stmt::For {
                variable,
                iterable,
                body,
            } => {
                // Simple for loop: generate a temporary array or use pointer iteration
                self.emit_indent();
                write!(self.output, "/* for {} in */ for (int _i = 0; _i < 10; _i++) {{", variable).unwrap();
                self.indent += 1;

                // TODO: Proper range/iterator support
                self.emit_indent();
                writeln!(self.output, "{} = _i;", variable).unwrap();

                for stmt in body {
                    self.emit_statement(stmt)?;
                }

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}}").unwrap();
            }
            Stmt::Guard { condition, else_body } => {
                self.emit_indent();
                write!(self.output, "if (!(").unwrap();
                self.emit_expression(condition)?;
                writeln!(self.output, ")) {{").unwrap();
                self.indent += 1;

                for stmt in else_body {
                    self.emit_statement(stmt)?;
                }

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}}").unwrap();
            }
            Stmt::Spawn(expr) => {
                self.emit_indent();
                write!(self.output, "/* spawn */ ").unwrap();
                self.emit_expression(expr)?;
                writeln!(self.output, ";").unwrap();
            }
        }

        Ok(())
    }

    fn emit_expression(&mut self, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::IntegerLiteral(value) => {
                write!(self.output, "{}", value).unwrap();
            }
            Expr::HexLiteral(value) => {
                write!(self.output, "0x{:x}", value).unwrap();
            }
            Expr::FloatLiteral(value) => {
                write!(self.output, "{}", value).unwrap();
            }
            Expr::StringLiteral(value) => {
                write!(self.output, "\"{}\"", value).unwrap();
            }
            Expr::BoolLiteral(value) => {
                write!(self.output, "{}", if *value { "1" } else { "0" }).unwrap();
            }
            Expr::Identifier(name) => {
                // Convert qualified name: math::add -> math_add
                let c_name = name.replace("::", "_");
                write!(self.output, "{}", c_name).unwrap();
            }
            Expr::BinaryOp { op, left, right } => {
                if matches!(op, BinOp::Concat) {
                    // String concatenation - convert non-string types to strings
                    write!(self.output, "concat_strings(").unwrap();
                    self.emit_to_string(left)?;
                    write!(self.output, ", ").unwrap();
                    self.emit_to_string(right)?;
                    write!(self.output, ")").unwrap();
                } else {
                    write!(self.output, "(").unwrap();
                    self.emit_expression(left)?;
                    let op_str = self.binop_to_c(op).to_string();
                    write!(self.output, " {} ", op_str).unwrap();
                    self.emit_expression(right)?;
                    write!(self.output, ")").unwrap();
                }
            }
            Expr::UnaryOp { op, expr } => {
                match op {
                    UnaryOp::Neg => write!(self.output, "-").unwrap(),
                    UnaryOp::Not => write!(self.output, "!").unwrap(),
                }
                self.emit_expression(expr)?;
            }
            Expr::Ref(expr) => {
                write!(self.output, "&").unwrap();
                self.emit_expression(expr)?;
            }
            Expr::Cast { expr, target_type } => {
                // C-style cast
                write!(self.output, "({})", self.type_to_c(target_type)).unwrap();
                write!(self.output, "(").unwrap();
                self.emit_expression(expr)?;
                write!(self.output, ")").unwrap();
            }
            Expr::FunctionCall { name, args } => {
                // Map Glyph built-in function names to C names
                let c_name = if let Expr::Identifier(n) = name.as_ref() {
                    Self::map_builtin_name_static(n)
                } else {
                    None
                };
                if let Some(cname) = c_name {
                    write!(self.output, "{}", cname).unwrap();
                } else {
                    self.emit_expression(name)?;
                }
                write!(self.output, "(").unwrap();
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        write!(self.output, ", ").unwrap();
                    }
                    self.emit_expression(arg)?;
                }
                write!(self.output, ")").unwrap();
            }
            Expr::MethodCall {
                object,
                method,
                args,
            } => {
                match method.as_str() {
                    "len" => {
                        write!(self.output, "strlen(").unwrap();
                        self.emit_expression(object)?;
                        write!(self.output, ")").unwrap();
                    }
                    "to_uint" => {
                        write!(self.output, "atoll(").unwrap();
                        self.emit_expression(object)?;
                        write!(self.output, ")").unwrap();
                    }
                    "append" => {
                        write!(self.output, "/* append */ ").unwrap();
                        self.emit_expression(object)?;
                    }
                    "send" => {
                        write!(self.output, "/* send */ ").unwrap();
                        self.emit_expression(object)?;
                        write!(self.output, "(").unwrap();
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                write!(self.output, ", ").unwrap();
                            }
                            self.emit_expression(arg)?;
                        }
                        write!(self.output, ")").unwrap();
                    }
                    "recv" => {
                        write!(self.output, "/* recv */ ").unwrap();
                        self.emit_expression(object)?;
                    }
                    _ => {
                        self.emit_expression(object)?;
                        write!(self.output, ".{}(", method).unwrap();
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                write!(self.output, ", ").unwrap();
                            }
                            self.emit_expression(arg)?;
                        }
                        write!(self.output, ")").unwrap();
                    }
                }
            }
            Expr::FieldAccess { object, field } => {
                self.emit_expression(object)?;
                write!(self.output, ".{}", field).unwrap();
            }
            Expr::IndexAccess { object, index } => {
                self.emit_expression(object)?;
                write!(self.output, "[").unwrap();
                self.emit_expression(index)?;
                write!(self.output, "]").unwrap();
            }
            Expr::StructInit { name, fields } => {
                write!(self.output, "({}){{", name).unwrap();
                for (i, (field_name, field_value)) in fields.iter().enumerate() {
                    if i > 0 {
                        write!(self.output, ", ").unwrap();
                    }
                    write!(self.output, ".{} = ", field_name).unwrap();
                    self.emit_expression(field_value)?;
                }
                write!(self.output, "}}").unwrap();
            }
            Expr::EnumInit { enum_name, variant, args } => {
                // Generate: (EnumName){ .tag = EnumName_Tag_Variant, .data.Variant.field0 = arg0, ... }
                write!(self.output, "({}){{ .tag = {}_Tag_{}, ", enum_name, enum_name, variant).unwrap();
                for (i, arg) in args.iter().enumerate() {
                    write!(self.output, ".data.{}.field{} = ", variant, i).unwrap();
                    self.emit_expression(arg)?;
                    write!(self.output, ", ").unwrap();
                }
                write!(self.output, "}}").unwrap();
            }
            Expr::Match { expr, arms } => {
                // Use GNU Statement Expression for match with nested ternary
                writeln!(self.output, "({{").unwrap();
                self.indent += 1;

                // Evaluate match expression once
                // Check if expression is a reference type and dereference
                let is_ref = self.is_ref_expression(expr);
                self.emit_indent();
                if is_ref {
                    write!(self.output, "__auto_type _match_val = *").unwrap();
                } else {
                    write!(self.output, "__auto_type _match_val = ").unwrap();
                }
                self.emit_expression(expr)?;
                writeln!(self.output, ";").unwrap();

                // Generate flat ternary chain: cond1 ? body1 : cond2 ? body2 : body3
                self.emit_indent();
                for (i, arm) in arms.iter().enumerate() {
                    if i > 0 {
                        write!(self.output, " : ").unwrap();
                    }

                    // Generate condition (skip for last arm - it's the default)
                    if i < arms.len() - 1 {
                        match &arm.pattern {
                            Pattern::IntegerLiteral(v) => {
                                write!(self.output, "(_match_val == {}) ? ", v).unwrap();
                            }
                            Pattern::StringLiteral(s) => {
                                write!(self.output, "(strcmp(_match_val, \"{}\") == 0) ? ", s).unwrap();
                            }
                            Pattern::BoolLiteral(b) => {
                                write!(self.output, "(_match_val == {}) ? ", if *b { "1" } else { "0" }).unwrap();
                            }
                            Pattern::Identifier(_) | Pattern::Wildcard => {
                                // Wildcard/identifier is always true, skip condition
                            }
                            Pattern::EnumVariant { enum_name, variant, .. } => {
                                let type_name = enum_name.as_deref().unwrap_or("");
                                write!(self.output, "(_match_val.tag == {}_Tag_{}) ? ", type_name, variant).unwrap();
                            }
                        }
                    }

                    // Generate arm body
                    write!(self.output, "({{ ").unwrap();
                    match &arm.pattern {
                        Pattern::Identifier(name) => {
                            write!(self.output, "__auto_type {} = _match_val; ", name).unwrap();
                        }
                        Pattern::EnumVariant { variant, data: Some(data_patterns), .. } => {
                            for (i, dp) in data_patterns.iter().enumerate() {
                                if let Pattern::Identifier(name) = dp {
                                    write!(self.output, "__auto_type {} = _match_val.data.{}.field{}; ", name, variant, i).unwrap();
                                }
                            }
                        }
                        _ => {}
                    }
                    self.emit_expression(&arm.body)?;
                    write!(self.output, "; }})").unwrap();
                }
                writeln!(self.output, ";").unwrap();

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}})").unwrap();
            }
            Expr::If {
                condition,
                then_branch,
                else_branch,
            } => {
                // Use GNU Statement Expression for if expression
                writeln!(self.output, "({{").unwrap();
                self.indent += 1;

                self.emit_indent();
                write!(self.output, "if (").unwrap();
                self.emit_expression(condition)?;
                writeln!(self.output, ") {{").unwrap();
                self.indent += 1;

                self.emit_expression(then_branch)?;
                writeln!(self.output, ";").unwrap();

                self.indent -= 1;

                if let Some(else_expr) = else_branch {
                    self.emit_indent();
                    writeln!(self.output, "}} else {{").unwrap();
                    self.indent += 1;

                    self.emit_expression(else_expr)?;
                    writeln!(self.output, ";").unwrap();

                    self.indent -= 1;
                }

                self.emit_indent();
                writeln!(self.output, "}}").unwrap();

                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}})").unwrap();
            }
            Expr::Block(stmts) => {
                // Use GNU Statement Expression
                writeln!(self.output, "({{").unwrap();
                self.indent += 1;
                for stmt in stmts {
                    self.emit_statement(stmt)?;
                }
                self.indent -= 1;
                self.emit_indent();
                writeln!(self.output, "}})").unwrap();
            }
            Expr::Range { start, end, inclusive } => {
                // Emit range as start value (range is only valid in for loops)
                // This is a placeholder - actual range handling is in for loop codegen
                self.emit_expression(start)?;
            }
            Expr::ArrayLiteral(elements) => {
                // Emit as C array initializer
                write!(self.output, "(int64_t[]){{").unwrap();
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        write!(self.output, ", ").unwrap();
                    }
                    self.emit_expression(elem)?;
                }
                write!(self.output, "}}").unwrap();
            }
            Expr::ChannelBounded { capacity: _ } => {
                write!(self.output, "/* channel */").unwrap();
            }
            Expr::Await(expr) => {
                self.emit_expression(expr)?;
                write!(self.output, " /* await */").unwrap();
            }
        }

        Ok(())
    }

    fn type_to_c(&self, ty: &Type) -> String {
        match ty {
            Type::String => "char*".to_string(),
            Type::UInt64 => "uint64_t".to_string(),
            Type::Int64 => "int64_t".to_string(),
            Type::Float64 => "double".to_string(),
            Type::Bool => "int".to_string(),
            Type::Void => "void".to_string(),
            Type::Bytes => "char*".to_string(),
            Type::List(_) => "void*".to_string(),
            Type::Map(_, _) => "void*".to_string(),
            Type::Result(_, _) => "void*".to_string(),
            Type::Option(_) => "void*".to_string(),
            Type::Async(_) => "void*".to_string(),
            Type::Channel(_) => "void*".to_string(),
            Type::Array(inner, size) => format!("{}[{}]", self.type_to_c(inner), size),
            Type::Ref(inner) => format!("{}*", self.type_to_c(inner)),
            Type::Custom(name) => name.clone(),
        }
    }

    fn binop_to_c(&self, op: &BinOp) -> &str {
        match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Mod => "%",
            BinOp::Concat => "/* concat */",
            BinOp::Eq => "==",
            BinOp::Neq => "!=",
            BinOp::Lt => "<",
            BinOp::Gt => ">",
            BinOp::Le => "<=",
            BinOp::Ge => ">=",
            BinOp::And => "&&",
            BinOp::Or => "||",
        }
    }

    /// Check if a match expression evaluates to a reference type (pointer)
    fn is_ref_expression(&self, expr: &Expr) -> bool {
        match expr {
            // Explicit reference: &x
            Expr::Ref(_) => true,
            // Identifier: check variable types
            Expr::Identifier(name) => {
                matches!(self.variable_types.get(name), Some(Type::Ref(_)))
            }
            _ => false,
        }
    }

    fn emit_to_string(&mut self, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::IntegerLiteral(_) => {
                write!(self.output, "int64_to_string(").unwrap();
                self.emit_expression(expr)?;
                write!(self.output, ")").unwrap();
                Ok(())
            }
            Expr::FloatLiteral(_) => {
                write!(self.output, "float64_to_string(").unwrap();
                self.emit_expression(expr)?;
                write!(self.output, ")").unwrap();
                Ok(())
            }
            Expr::StringLiteral(_) => {
                self.emit_expression(expr)
            }
            Expr::Identifier(_) => {
                self.emit_expression(expr)
            }
            _ => self.emit_expression(expr),
        }
    }

    fn emit_builtin_functions(&mut self) {
        writeln!(self.output, "// =====================").unwrap();
        writeln!(self.output, "// Glyph Built-in Runtime").unwrap();
        writeln!(self.output, "// =====================").unwrap();
        writeln!(self.output, "").unwrap();

        // Core runtime
        writeln!(self.output, "void glyph_println(const char* msg) {{ printf(\"%s\\n\", msg); }}").unwrap();
        writeln!(self.output, "void glyph_eprintln(const char* msg) {{ fprintf(stderr, \"%s\\n\", msg); }}").unwrap();
        writeln!(self.output, "void glyph_print_int(int64_t v) {{ printf(\"%ld\\n\", v); }}").unwrap();
        writeln!(self.output, "void glyph_print_float(double v) {{ printf(\"%f\\n\", v); }}").unwrap();
        writeln!(self.output, "void glyph_print_bool(int v) {{ printf(\"%s\\n\", v ? \"true\" : \"false\"); }}").unwrap();
        writeln!(self.output, "").unwrap();

        // String functions
        writeln!(self.output, "char* glyph_concat_strings(const char* a, const char* b) {{").unwrap();
        writeln!(self.output, "    size_t la = strlen(a), lb = strlen(b);").unwrap();
        writeln!(self.output, "    char* r = (char*)malloc(la + lb + 1);").unwrap();
        writeln!(self.output, "    memcpy(r, a, la); memcpy(r + la, b, lb + 1);").unwrap();
        writeln!(self.output, "    return r;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "char* glyph_int_to_string(int64_t v) {{").unwrap();
        writeln!(self.output, "    char* b = (char*)malloc(32); snprintf(b, 32, \"%ld\", v); return b;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "char* glyph_float_to_string(double v) {{").unwrap();
        writeln!(self.output, "    char* b = (char*)malloc(64); snprintf(b, 64, \"%f\", v); return b;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "char* glyph_bool_to_string(int v) {{ return v ? strdup(\"true\") : strdup(\"false\"); }}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "int64_t glyph_strlen(const char* s) {{ return (int64_t)strlen(s); }}").unwrap();
        writeln!(self.output, "char* glyph_substring(const char* s, int64_t start, int64_t end) {{").unwrap();
        writeln!(self.output, "    int64_t len = strlen(s);").unwrap();
        writeln!(self.output, "    if (start < 0) start = 0; if (end > len) end = len;").unwrap();
        writeln!(self.output, "    if (start >= end) return strdup(\"\");").unwrap();
        writeln!(self.output, "    char* r = (char*)malloc(end - start + 1);").unwrap();
        writeln!(self.output, "    memcpy(r, s + start, end - start); r[end - start] = 0; return r;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "int glyph_str_contains(const char* s, const char* sub) {{ return strstr(s, sub) != NULL; }}").unwrap();
        writeln!(self.output, "int glyph_str_starts_with(const char* s, const char* p) {{ return strncmp(s, p, strlen(p)) == 0; }}").unwrap();
        writeln!(self.output, "int glyph_str_ends_with(const char* s, const char* sfx) {{").unwrap();
        writeln!(self.output, "    size_t ls = strlen(s), lf = strlen(sfx);").unwrap();
        writeln!(self.output, "    return ls >= lf && strcmp(s + ls - lf, sfx) == 0;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "char* glyph_str_trim(const char* s) {{").unwrap();
        writeln!(self.output, "    while (*s && (*s == ' ' || *s == '\\t' || *s == '\\n' || *s == '\\r')) s++;").unwrap();
        writeln!(self.output, "    const char* e = s + strlen(s) - 1;").unwrap();
        writeln!(self.output, "    while (e > s && (*e == ' ' || *e == '\\t' || *e == '\\n' || *e == '\\r')) e--;").unwrap();
        writeln!(self.output, "    size_t len = e - s + 1;").unwrap();
        writeln!(self.output, "    char* r = (char*)malloc(len + 1); memcpy(r, s, len); r[len] = 0; return r;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "char* glyph_str_to_upper(const char* s) {{").unwrap();
        writeln!(self.output, "    size_t l = strlen(s); char* r = (char*)malloc(l + 1);").unwrap();
        writeln!(self.output, "    for (size_t i = 0; i < l; i++) r[i] = (s[i] >= 'a' && s[i] <= 'z') ? s[i] - 32 : s[i];").unwrap();
        writeln!(self.output, "    r[l] = 0; return r;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "char* glyph_str_to_lower(const char* s) {{").unwrap();
        writeln!(self.output, "    size_t l = strlen(s); char* r = (char*)malloc(l + 1);").unwrap();
        writeln!(self.output, "    for (size_t i = 0; i < l; i++) r[i] = (s[i] >= 'A' && s[i] <= 'Z') ? s[i] + 32 : s[i];").unwrap();
        writeln!(self.output, "    r[l] = 0; return r;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "char glyph_char_at(const char* s, int64_t i) {{").unwrap();
        writeln!(self.output, "    if (i < 0 || i >= (int64_t)strlen(s)) return 0; return s[i];").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        // Parse functions
        writeln!(self.output, "OptionInt glyph_parse_int(const char* s) {{").unwrap();
        writeln!(self.output, "    char* end; long v = strtol(s, &end, 10);").unwrap();
        writeln!(self.output, "    if (end == s) return (OptionInt){{0, 0}}; return (OptionInt){{1, v}};").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "OptionFloat glyph_parse_float(const char* s) {{").unwrap();
        writeln!(self.output, "    char* end; double v = strtod(s, &end);").unwrap();
        writeln!(self.output, "    if (end == s) return (OptionFloat){{0, 0.0}}; return (OptionFloat){{1, v}};").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        // Math functions (use <math.h>)
        writeln!(self.output, "double glyph_abs(double x) {{ return x < 0 ? -x : x; }}").unwrap();
        writeln!(self.output, "double glyph_min(double a, double b) {{ return a < b ? a : b; }}").unwrap();
        writeln!(self.output, "double glyph_max(double a, double b) {{ return a > b ? a : b; }}").unwrap();
        writeln!(self.output, "double glyph_sqrt(double x) {{ return sqrt(x); }}").unwrap();
        writeln!(self.output, "double glyph_pow(double b, double e) {{ return pow(b, e); }}").unwrap();
        writeln!(self.output, "double glyph_floor(double x) {{ return floor(x); }}").unwrap();
        writeln!(self.output, "double glyph_ceil(double x) {{ return ceil(x); }}").unwrap();
        writeln!(self.output, "double glyph_round(double x) {{ return round(x); }}").unwrap();
        writeln!(self.output, "double glyph_log(double x) {{ return log(x); }}").unwrap();
        writeln!(self.output, "double glyph_log2(double x) {{ return log2(x); }}").unwrap();
        writeln!(self.output, "double glyph_log10(double x) {{ return log10(x); }}").unwrap();
        writeln!(self.output, "double glyph_sin(double x) {{ return sin(x); }}").unwrap();
        writeln!(self.output, "double glyph_cos(double x) {{ return cos(x); }}").unwrap();
        writeln!(self.output, "double glyph_tan(double x) {{ return tan(x); }}").unwrap();
        writeln!(self.output, "").unwrap();

        // File I/O
        writeln!(self.output, "").unwrap();
        writeln!(self.output, "char* glyph_file_read(const char* path) {{").unwrap();
        writeln!(self.output, "    FILE* f = fopen(path, \"rb\");").unwrap();
        writeln!(self.output, "    if (!f) return strdup(\"\");").unwrap();
        writeln!(self.output, "    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);").unwrap();
        writeln!(self.output, "    char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0; fclose(f);").unwrap();
        writeln!(self.output, "    return buf;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "int glyph_file_write(const char* path, const char* content) {{").unwrap();
        writeln!(self.output, "    FILE* f = fopen(path, \"wb\"); if (!f) return 0;").unwrap();
        writeln!(self.output, "    fwrite(content, 1, strlen(content), f); fclose(f); return 1;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "int glyph_file_append(const char* path, const char* content) {{").unwrap();
        writeln!(self.output, "    FILE* f = fopen(path, \"ab\"); if (!f) return 0;").unwrap();
        writeln!(self.output, "    fwrite(content, 1, strlen(content), f); fclose(f); return 1;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "int glyph_file_exists(const char* path) {{").unwrap();
        writeln!(self.output, "    FILE* f = fopen(path, \"r\"); if (f) {{ fclose(f); return 1; }} return 0;").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "int glyph_create_dir(const char* path) {{").unwrap();
        writeln!(self.output, "    #ifdef _WIN32").unwrap();
        writeln!(self.output, "    return _mkdir(path) == 0;").unwrap();
        writeln!(self.output, "    #else").unwrap();
        writeln!(self.output, "    return mkdir(path, 0755) == 0;").unwrap();
        writeln!(self.output, "    #endif").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "int glyph_remove_file(const char* path) {{ return remove(path) == 0; }}").unwrap();
        writeln!(self.output, "").unwrap();

        // Assert
        writeln!(self.output, "void glyph_assert(int cond, const char* msg) {{").unwrap();
        writeln!(self.output, "    if (!cond) {{ fprintf(stderr, \"Assertion failed: %s\\n\", msg); abort(); }}").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "void glyph_assert_eq(const char* a, const char* b, const char* msg) {{").unwrap();
        writeln!(self.output, "    if (strcmp(a, b) != 0) {{ fprintf(stderr, \"Assertion failed: %s (got '%s' vs '%s')\\n\", msg, a, b); abort(); }}").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "void glyph_assert_ne(const char* a, const char* b, const char* msg) {{").unwrap();
        writeln!(self.output, "    if (strcmp(a, b) == 0) {{ fprintf(stderr, \"Assertion failed: %s (both '%s')\\n\", msg, a); abort(); }}").unwrap();
        writeln!(self.output, "}}").unwrap();
        writeln!(self.output, "").unwrap();

        // Memory
        writeln!(self.output, "void* glyph_alloc(int64_t size) {{ return malloc((size_t)size); }}").unwrap();
        writeln!(self.output, "void glyph_free(void* p) {{ free(p); }}").unwrap();
        writeln!(self.output, "").unwrap();

        writeln!(self.output, "// =====================").unwrap();
        writeln!(self.output, "").unwrap();
    }

    fn map_builtin_name_static(name: &str) -> Option<&'static str> {
        match name {
            // io
            "print" | "println" => Some("glyph_println"),
            "eprintln" => Some("glyph_eprintln"),
            "print_int" => Some("glyph_print_int"),
            "print_float" => Some("glyph_print_float"),
            "print_bool" => Some("glyph_print_bool"),
            // string
            "len" => Some("glyph_strlen"),
            "concat" => Some("glyph_concat_strings"),
            "int_to_string" => Some("glyph_int_to_string"),
            "float_to_string" => Some("glyph_float_to_string"),
            "bool_to_string" => Some("glyph_bool_to_string"),
            "substring" => Some("glyph_substring"),
            "contains" => Some("glyph_str_contains"),
            "starts_with" => Some("glyph_str_starts_with"),
            "ends_with" => Some("glyph_str_ends_with"),
            "trim" => Some("glyph_str_trim"),
            "to_upper" => Some("glyph_str_to_upper"),
            "to_lower" => Some("glyph_str_to_lower"),
            "char_at" => Some("glyph_char_at"),
            "parse_int" => Some("glyph_parse_int"),
            "parse_float" => Some("glyph_parse_float"),
            // math
            "abs" => Some("glyph_abs"),
            "min" => Some("glyph_min"),
            "max" => Some("glyph_max"),
            "sqrt" => Some("glyph_sqrt"),
            "pow" => Some("glyph_pow"),
            "floor" => Some("glyph_floor"),
            "ceil" => Some("glyph_ceil"),
            "round" => Some("glyph_round"),
            "log" => Some("glyph_log"),
            "log2" => Some("glyph_log2"),
            "log10" => Some("glyph_log10"),
            "sin" => Some("glyph_sin"),
            "cos" => Some("glyph_cos"),
            "tan" => Some("glyph_tan"),
            // fs
            "file_read" => Some("glyph_file_read"),
            "file_write" => Some("glyph_file_write"),
            "file_append" => Some("glyph_file_append"),
            "file_exists" => Some("glyph_file_exists"),
            "create_dir" => Some("glyph_create_dir"),
            "remove_file" => Some("glyph_remove_file"),
            // mem
            "alloc" => Some("glyph_alloc"),
            "free" => Some("glyph_free"),
            // assert
            "assert" => Some("glyph_assert"),
            "assert_eq" => Some("glyph_assert_eq"),
            "assert_ne" => Some("glyph_assert_ne"),
            _ => None,
        }
    }

    fn emit_indent(&mut self) {
        for _ in 0..self.indent {
            write!(self.output, "    ").unwrap();
        }
    }
}

pub fn compile_to_c(program: &Program, output_path: &str) -> Result<(), CodegenError> {
    let mut codegen = CCodegen::new();
    let c_code = codegen.compile(program)?;

    std::fs::write(output_path, c_code).map_err(|_e| CodegenError::CannotGenerateExpression)?;

    Ok(())
}
